<br />
<form id="processos" name="processos" action="/comarca/visualizar" method="post">
<table border="0" width="100%">
	<tr>
		<td colspan="8" nowrap="nowrap">
			<input type="text" id="parametrobusca" name="parametrobusca" value="" class="input" style="width:89%">
			<input type="submit" id="buscar" name="buscar" value="Pesquisar" class="button" width="10%">
		</td>
	</tr>
	<tr><td colspan="8">&nbsp;</td></tr>
</table>
<table border="0" class="lista_naturezas" align="center">
	<tr>
		<td align="center" colspan="8" class="message"><?= $this->message; ?></td>
	</tr>
	<?php if ($this->nmcomarcas > 0): ?>
	<tr><td align="center" colspan="8">Foram encontrados <strong><?=$this->nmcomarcas ?></strong> comarcas cadastradas</td></tr>
	<tr>
		<td nowrap="nowrap" class="brancob_11"  bgcolor="gray">Nome</td>
		<td nowrap="nowrap" class="brancob_11"  bgcolor="gray">&nbsp;</td>
	</tr>
	<?php else: ?>
	<tr><td align="center" colspan="8" class="message">Nenhuma comarca foi encontrada!</td></tr>	
	<?php endif; ?>
	<?php $i = 0?>
	<?php foreach($this->comarcas as $comarca) : ?>
	<?php $bgcolor = ($i % 2 == 0) ? "#eeeeee" : "" ?>
	<tr background="#ded"> 
		<td nowrap="nowrap" class="cinza_11" bgcolor="<?=$bgcolor?>">
			<?php echo $comarca->nome; ?>			
		</td>
		
		<td nowrap="nowrap" bgcolor="<?=$bgcolor?>" width="50px">		
			<a href="<?= "/comarca/editar/id/" . $comarca->id?>">
				<img src="/images/editar.gif" border="0"></a>
			<a href="#" onclick="javascript:confirmExclusao('/comarca/excluir/id/' + <?=$comarca->id?>)">
				<img src="/images/excluir.gif" border="0"></a>
		</td>
	</tr>
	<?php $i++; ?>
	<?php endforeach; ?>

</table>
</form>