<br />
<form id="processos" name="processos" action="/cliente/visualizar" method="post">
<?php //echo time("22/12/2008");  
		//echo date("d/m/Y", "1239884007");
		//echo "|" . (string)$this->nmregistros; ?>
<table border="0" width="100%">
	<tr>
		<td colspan="8" nowrap="nowrap">
			<input type="text" id="parametrobusca" name="parametrobusca" value="" class="input" style="width:89%">
			<input type="submit" id="buscar" name="buscar" value="Pesquisar" class="button" width="10%">
		</td>
	</tr>
	<tr><td colspan="8">&nbsp;</td></tr>
</table>
<table border="0" class="lista_processos">
	<tr>
		<td align="center" colspan="8" class="message"><?= $this->message; ?></td>
	</tr>
	<?php if ($this->nmclientes > 0): ?>
	<tr><td align="center" colspan="8">Foram encontrados <strong><?=$this->nmclientes ?></strong> clientes cadastrados</td></tr>
	<tr>
		<td nowrap="nowrap" class="brancob_11"  bgcolor="gray">Nome</td>
		<td nowrap="nowrap" class="brancob_11"  bgcolor="gray">CPF</td>
		<td nowrap="nowrap" class="brancob_11"  bgcolor="gray">CNPJ</td>
		<td nowrap="nowrap" class="brancob_11"  bgcolor="gray">Endere&ccedil;o</td>
		<td nowrap="nowrap" class="brancob_11"  bgcolor="gray">Cidade</td>
		<td nowrap="nowrap" class="brancob_11"  bgcolor="gray">Estado</td>
		<td nowrap="nowrap" class="brancob_11"  bgcolor="gray">Telefone</td>
		<td nowrap="nowrap" class="brancob_11"  bgcolor="gray">Email</td>
		<td nowrap="nowrap" class="brancob_11"  bgcolor="gray">&nbsp;</td>
	</tr>
	<?php else: ?>
	<tr><td align="center" colspan="8" class="message">Nenhum cliente foi encontrado!</td></tr>	
	<?php endif; ?>
	<?php $i = 0?>
	<?php foreach($this->clientes as $cliente) : ?>
	<?php $bgcolor = ($i % 2 == 0) ? "#eeeeee" : "" ?>
	<tr background="#ded"> 
		<td nowrap="nowrap" class="cinza_11" bgcolor=<?=$bgcolor?>>
			<?php echo $cliente->nome; ?>			
		</td>
		<td nowrap="nowrap" class="cinza_11" bgcolor=<?=$bgcolor?>>		
			<?= $cliente->cpf; ?></td>
		<td nowrap="nowrap" class="cinza_11" bgcolor=<?=$bgcolor?>>
			<?= $cliente->cnpj; ?></td>
		<td nowrap="nowrap" class="cinza_11" bgcolor=<?=$bgcolor?>>
			<?= $cliente->endereco;?></td>
		<td nowrap="nowrap" class="cinza_11" bgcolor=<?=$bgcolor?>>
			<?= $cliente->cidade;?></td>
		<td nowrap="nowrap" class="cinza_11" bgcolor=<?=$bgcolor?>>
			<?=$cliente->estado;?></td>
		<td nowrap="nowrap" class="cinza_11" bgcolor=<?=$bgcolor?>>
			<?= $cliente->telefone;?></td>
		<td nowrap="nowrap" class="cinza_11" bgcolor=<?=$bgcolor?>>
			<?= $cliente->email;?></td>
		<td nowrap="nowrap" bgcolor=<?=$bgcolor?>>		
			<a href="<?= "/cliente/editar/id/" . $cliente->id?>">
				<img src="/images/editar.gif" border="0"></a>
			<a href="#" onclick="javascript:confirmExclusao('/cliente/excluir/id/' + <?=$cliente->id?>)">
				<img src="/images/excluir.gif" border="0"></a>
				
		</td>
	</tr>
	<?php $i++; ?>
	<?php endforeach; ?>

</table>
</form>

<?php 

function formataNumeroProcesso($nmProcesso) {
	// 023.95.052005-1
	// 239.50.520051-1
	// 023..9.5.0520-0 
	//substr('abcdef', 0, 4);  // abcd
	
	$parte1 = substr($nmProcesso, 1, 3);
	$parte2 = substr($nmProcesso, 4, 2);
	$parte3 = substr($nmProcesso, 6, 6);
	$parte4 = substr($nmProcesso, 11, 1);
	return $parte1 . "." . $parte2 . "." . $parte3 . "-" . $parte4;
}

?>