<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>Sistema de Consulta Jur&iacute;dica</title>
	<link rel="stylesheet" type="text/css" href="/sajproj/style/style.css">
    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-35184277-3']);
        _gaq.push(['_trackPageview']);

        (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>
</head>
<body>

<div id="tudo">
	<div id="conteudo">
		<div id="topo">
			<h1>SAJPROJ - SISTEMA DE AUTOMA&Ccedil;&Atilde;O JUR&Iacute;DICA</h1>
		</div>

		<div id="principal">
			<?= $this->layout()->content ?>
		</div> <!-- Fim da div#principal -->



		<div class="clear"></div>

	</div> <!-- Fim da div#conteudo -->

	<div id="rodape">

	</div>
</div> <!-- Fim da div#tudo -->

</body>
</html>