<p>&nbsp;</p>

<!-- Container para o calendario -->
<div id="container">
	<div class="hd"></div>

	<div class="bd">
		<div id="cal"></div>
	</div>
</div>
<!-- Fim container para o calendario -->

<!--begin custom header content for this example-->
<style type="text/css">
    /* Clear calendar's float 
    #container .bd:after {content:".";display:block;clear:left;height:0;visibility:hidden;}*/

    /* Have calendar squeeze upto bd bounding box */
    #container .bd {padding:0;}

    /* Remove calendar's border and set padding in ems instead of px, so we can specify an width in ems for the container
    #cal {border:none;padding:1em}*/

    /* Datefield look/feel 
    .datefield {
        position:relative;
        top:10px;
        left:10px;
        white-space:nowrap;
        border:1px solid black;
        background-color:#eee;
        width:25em;
        padding:5px;
    }

    .datefield input,
    .datefield button,
    .datefield label  {vertical-align:middle}

    .datefield label  {font-weight:bold}
    .datefield input  {width:15em}
    .datefield button  {padding:0 5px 0 5px; margin-left:2px;}
    .datefield button img {padding:0;margin:0;vertical-align:middle}*/

    /* Example box 
    .box {
		position:relative;
		height:30em;
    }*/
</style>
	
<form id="cadprocesso" name="cadprocesso" action="/index/<?= $this->action; ?>" method="post">
<table border="0" width="50%" align="center">
	<input type="hidden" name="id" value="<?= $this->id; ?>" >
	<tr>
		<td align="center" colspan="2" class="cinzab_11"><?= $this->subtitulo; ?></td>
	</tr>
	<tr>
		<td align="center" colspan="2" class="message"><?= $this->message; ?></td>
	</tr>
	<tr>
		<td class="cinza_11">N&uacute;mero do processo</td>
		<td>
			<input type="text" id="nmprocesso" name="nmprocesso" 
					value="<?= $this->numero_processo; ?>" class="input" style="width: 250px">
		</td>
	</tr>
	<tr>
		<td class="cinza_11" nowrap="nowrap">Data Distribui&ccedil;&atilde;o / Encerramento</td>

		<td class="cinza_11">
			<input type="text" id="dtdistribuicao" name="dtdistribuicao" class="input" style="width: 100px" readonly="readonly"
					value="<?= empty($this->data_distribuicao) ? "" : date("d/m/Y", $this->data_distribuicao); ?>" />
			<img id="showdd" src="/images/calendar.png" align="absmiddle" width="18px" height="18px"
					onclick="javascript:showCalendar('dtdistribuicao', 'container', 'showdd', 'cal');">
		<!--</td>
		
		<td class="cinza_11">-->
			<input type="text" id="dtencerramento" name="dtencerramento" class="input" style="width: 100px" readonly="readonly"
					value="<?= empty($this->data_encerramento) ? "" : date("d/m/Y", $this->data_encerramento); ?>" />
			<img id="showde" src="/images/calendar.png" align="absmiddle" width="18px" height="18px"
					onclick="javascript:showCalendar('dtencerramento', 'container', 'showde', 'cal');">
		</td>
		<!-- <td>
			<input type="text" id="dtdistribuicao" name="dtdistribuicao" 
					value="<?//= empty($this->data_distribuicao) ? "" : date("d/m/Y", $this->data_distribuicao); ?>" 
					class="input" style="width: 160px"><a class="cinza_11"> (dd/mm/aaaa)</a>
		</td> -->
	</tr>
	<!--<tr>
		<td class="cinza_11">Data Encerramento</td>
		
		<td class="cinza_11">
			<input type="text" id="dtencerramento" name="dtencerramento" class="input" style="width: 160px" readonly="readonly"
					value="<?//= empty($this->data_encerramento) ? "" : date("d/m/Y", $this->data_encerramento); ?>" />
			<img id="showde" src="/images/calendar.png" align="absmiddle" width="18px" height="18px"
					onclick="javascript:showCalendar('dtencerramento', 'container', 'showde', 'cal');">
		</td>
		<!--<div id="container">
			<div class="hd"></div>

			<div class="bd">
				<div id="cal"></div>
			</div>
		</div>
		
		<!--<td>
			<input type="text" id="dtencerramento" name="dtencerramento" 
					value="<?//= empty($this->data_encerramento) ? "" : date("d/m/Y", $this->data_encerramento); ?>" 
					class="input" style="width: 160px"><a class="cinza_11"> (dd/mm/aaaa)</a>
		</td>
	</tr>-->
	<tr>
		<td class="cinza_11">Cliente</td>
		<td>
			<select id="idcliente" name="idcliente" class="select" style="width: 253px">
			<?php foreach($this->clientes as $cliente) : ?>
				<?php if ($cliente->id == $this->cliente) : ?>
					<option selected value="<?= $cliente->id; ?>"><?= $cliente->nome; ?></option>
				<?php else : ?>
					<option value="<?= $cliente->id; ?>"><?= $cliente->nome; ?></option>
				<?php endif; ?>
			<?php endforeach; ?>
			</select>
		</td>
	</tr>
	<tr>
		<td class="cinza_11">Natureza</td>
		<td>
			<select id="idnatureza" name="idnatureza" class="select" style="width: 253px">
			<?php foreach($this->naturezas as $natureza) : ?>
				<?php if ($natureza->id == $this->natureza) : ?>
					<option selected value="<?= $natureza->id; ?>"><?= $natureza->nome; ?></option>
				<?php else : ?>
					<option value="<?= $natureza->id; ?>"><?= $natureza->nome; ?></option>
				<?php endif; ?>
			<?php endforeach; ?>
			</select>
		</td>
	</tr>
	<tr>
		<td class="cinza_11">Comarca</td>
		<td>
			<select id="idcomarca" name="idcomarca" class="select" style="width: 253px">
			<?php foreach($this->comarcas as $comarca) : ?>
				<?php if ($comarca->id == $this->comarca) : ?>
					<option selected value="<?= $comarca->id; ?>"><?= $comarca->nome; ?></option>
				<?php else : ?>
					<option value="<?= $comarca->id; ?>"><?= $comarca->nome; ?></option>
				<?php endif; ?>
			<?php endforeach; ?>
			</select>
		</td>
	</tr>
	<tr>
		<td class="cinza_11">Vara</td>
		<td>
			<select id="idvara" name="idvara" class="select" style="width: 253px">
			<?php foreach($this->varas as $vara) : ?>
				<?php if ($vara->id == $this->vara) : ?>
					<option selected value="<?= $vara->id; ?>"><?= $vara->nome; ?></option>
				<?php else : ?>
					<option value="<?= $vara->id; ?>"><?= $vara->nome; ?></option>
				<?php endif; ?>				
			<?php endforeach; ?>
			</select>
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td>
			<input type="submit" id="cadastrar" name="cadastrar" value="<?= $this->textButton; ?>" class="button">
		</td>
	</tr>
	
</table>
</form>
