
<!-- <form id="processos" name="processos" action="/parte/visualizar" method="post"> -->

<!--<table border="0" width="100%">
	 <tr>
		<td colspan="8" nowrap="nowrap">
			<input type="text" id="parametrobusca" name="parametrobusca" value="" class="input" style="width:89%">
			<input type="submit" id="buscar" name="buscar" value="Pesquisar" class="button" width="10%">
		</td>
	</tr> 
	<tr><td colspan="8">&nbsp;</td></tr>
</table>-->
<br />
<table border="0" class="lista_naturezas" align="center">
	<tr><td>&nbsp;</td></tr>
	<?php if ($this->nmpartes > 0): ?>
	<tr>
		<td align="center" colspan="8">
			Foram encontradas <strong><?=$this->nmpartes ?></strong> partes cadastradas para o processo selecionado.
		</td>
	</tr>
	<tr><td>&nbsp;</td></tr>
	<tr>
		<td nowrap="nowrap" class="brancob_11"  bgcolor="gray">Processo</td>
		<td nowrap="nowrap" class="brancob_11"  bgcolor="gray">Nome</td>
		<td nowrap="nowrap" class="brancob_11"  bgcolor="gray">Matr&iacute;cula</td>
		<td nowrap="nowrap" class="brancob_11"  bgcolor="gray">CPF</td>
		<td nowrap="nowrap" class="brancob_11"  bgcolor="gray">RG</td>
		<td nowrap="nowrap" class="brancob_11"  bgcolor="gray">&nbsp;</td>
	</tr>
	
	<?php endif; ?>
	<?php $i = 0?>
	<?php foreach($this->partes as $parte) : ?>
	<?php $bgcolor = ($i % 2 == 0) ? "#eeeeee" : "" ?>
	<tr background="#ded">
		<td nowrap="nowrap" class="cinza_11" bgcolor=<?=$bgcolor?>>
			<?php echo $parte->findParentProcesso()->numero_processo; ?>			
		</td>
		<td nowrap="nowrap" class="cinza_11" bgcolor=<?=$bgcolor?>>
			<?php echo $parte->nome_parte; ?>			
		</td>
		<td nowrap="nowrap" class="cinza_11" bgcolor=<?=$bgcolor?>>
			<?php echo $parte->numero_matricula; ?>			
		</td>
		<td nowrap="nowrap" class="cinza_11" bgcolor=<?=$bgcolor?>>
			<?php echo $parte->cpf; ?>			
		</td>
		<td nowrap="nowrap" class="cinza_11" bgcolor=<?=$bgcolor?>>
			<?php echo $parte->rg; ?>			
		</td>
		
		<td nowrap="nowrap" bgcolor=<?=$bgcolor?> width="50px">		
			<a href="<?= "/sajproj/parte/editar/id/" . $parte->id?>">
				<img src="/images/editar.gif" border="0"></a>			
			<a href="<?= "/sajproj/parte/excluir/id/" . $parte->id?>">
				<img src="/images/excluir.gif" border="0"></a>
				
		</td>
	</tr>
	<?php $i++; ?>
	<?php endforeach; ?>

</table>
<!--</form> -->