<ul id="menu">
	<li><a href="/">In&iacute;cio</a></li>
	<li><a>Processos</a>
	<ul>
		<li><a href="/index/cadastrar">&nbsp;Cadastrar&nbsp;</a></li>
		<li><a href="/">&nbsp;Visualizar&nbsp;</a></li>
	</ul>
	</li>
	<li><a>&nbsp;&nbsp;Partes&nbsp;&nbsp;&nbsp;</a>
	<ul>
		<li><a href="/parte/cadastrar">Cadastrar</a></li>
		<li><a href="/parte/visualizar">Visualizar</a></li>
	</ul>
	</li>
	<li><a>&nbsp;&nbsp;&nbsp;Cliente&nbsp;&nbsp;</a>
	<ul>
		<li><a href="/cliente/cadastrar">Cadastrar</a></li>
		<li><a href="/cliente/visualizar">Visualizar</a></li>
	</ul>
	</li>
	<li><a>&nbsp;&nbsp;&nbsp;Clientes/Contatos&nbsp;&nbsp;</a>
	<ul>
	<!-- 
		<li><a href="/cliente/cadastrar">Cadastrar</a></li>
	 -->
		<li><a href="/clientes/visualizar">Visualizar</a></li>
	</ul>
	</li>
	<li><a>&nbsp;Natureza</a>
	<ul>
		<li><a href="/natureza/cadastrar">Cadastrar</a></li>
		<li><a href="/natureza/visualizar">Visualizar</a></li>
	</ul>
	</li>
	<li><a>&nbsp;Comarca&nbsp;</a>
	<ul>
		<li><a href="/comarca/cadastrar">Cadastrar</a></li>
		<li><a href="/comarca/visualizar">Visualizar</a></li>
	</ul>
	</li>
	<li><a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Vara&nbsp;&nbsp;&nbsp;&nbsp;</a>
	<ul>
		<li><a href="/vara/cadastrar">Cadastrar</a></li>
		<li><a href="/vara/visualizar">Visualizar</a></li>
	</ul>
	</li>
	<li><a href="/sajproj/auth/logout">Sair</a></li>
</ul>