<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
        "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8">        
        <!-- Standard reset, fonts and grids -->

        <!--<link rel="stylesheet" type="text/css" href="/script/yui/reset-fonts-grids/reset-fonts-grids.css">-->


        <!-- CSS for Menu -->

        <link rel="stylesheet" type="text/css" href="/sajproj/script/yui/menu/assets/skins/sam/menu.css">  


        <!-- Page-specific styles -->

        <style type="text/css">

            /*div.yui-b p {
            
                margin: 0 0 .5em 0;
                color: #999;
            
            }
            
            div.yui-b p strong {
            
                font-weight: bold;
                color: #000;
            
            }
            
            div.yui-b p em {

                color: #000;
            
            }            
            
            h1 {

                font-weight: bold;
                margin: 0 0 1em 0;
                padding: .25em .5em;
                background-color: #ccc;

            }

            #productsandservices {

                margin: 0 0 10px 0;
            
            }*/

        </style>


        <!-- Dependency source files -->

        <script type="text/javascript" src="/sajproj/script/yui/yahoo-dom-event/yahoo-dom-event.js"></script>
        <script type="text/javascript" src="/sajproj/script/yui/container/container_core.js"></script>


        <!-- Menu source file -->

        <script type="text/javascript" src="/sajproj/script/yui/menu/menu.js"></script>


        <!-- Page-specific script -->

        <script type="text/javascript">

            /*
                 Initialize and render the MenuBar when its elements are ready 
                 to be scripted.
            */

            YAHOO.util.Event.onContentReady("productsandservices", function () {

                /*
                     Instantiate a MenuBar:  The first argument passed to the 
                     constructor is the id of the element in the page 
                     representing the MenuBar; the second is an object literal 
                     of configuration properties.
                */

                var oMenuBar = new YAHOO.widget.MenuBar("productsandservices", { 
                                                            autosubmenudisplay: false, 
                                                            hidedelay: 750, 
                                                            lazyload: false });

                /*
                     Define an array of object literals, each containing 
                     the data necessary to create a submenu.
                */

                var aSubmenuData = [
                    {
                        id: "inicio", 
                        itemdata: [ 
                            { text: "360", url: "http://360.yahoo.com" },
                            { text: "Alerts", url: "http://alerts.yahoo.com" },
                            { text: "Avatars", url: "http://avatars.yahoo.com" },
                            { text: "Groups", url: "http://groups.yahoo.com " },
                            { text: "Internet Access", url: "http://promo.yahoo.com/broadband" },
                            /*{
                                text: "PIM", 
                                submenu: { 
                                            id: "pim", 
                                            itemdata: [
                                                { text: "Yahoo! Mail", url: "http://mail.yahoo.com" },
                                                { text: "Yahoo! Address Book", url: "http://addressbook.yahoo.com" },
                                                { text: "Yahoo! Calendar",  url: "http://calendar.yahoo.com" },
                                                { text: "Yahoo! Notepad", url: "http://notepad.yahoo.com" }
                                            ] 
                                        }
                            
                            }, */
                            { text: "Member Directory", url: "http://members.yahoo.com" },
                            { text: "Messenger", url: "http://messenger.yahoo.com" },
                            { text: "Mobile", url: "http://mobile.yahoo.com" },
                            { text: "Flickr Photo Sharing", url: "http://www.flickr.com" },
                        ]
                    },

                    {
                        id: "processo", 
                        itemdata: [
                            { text: "Cadastrar", url: "/sajproj/index/cadastrar" },
                            { text: "Visualizar", url: "/sajproj/" }                    
                        ]    
                    },
                    
                    {
                        id: "parte", 
                        itemdata: [
                            { text: "Cadastrar", url: "/sajproj/parte/cadastrar" },
                            { text: "Visualizar", url: "/sajproj/parte/visualizar" }              
                        ] 
                    },
/*
                    {
                        id: "cliente", 
                        itemdata: [
                            { text: "Cadastrar", url: "/sajproj/cliente/cadastrar" },
                            { text: "Visualizar", url: "/sajproj/cliente/visualizar" }              
                        ] 
                    },
*/
                    {
                        id: "clientes", 
                        itemdata: [
                            { text: "Cadastrar", url: "/sajproj/cliente/cadastrar" },
                            { text: "Visualizar", url: "/sajproj/cliente/visualizar" }              
                        ] 
                    },

                    {
                        id: "natureza", 
                        itemdata: [
                            { text: "Cadastrar", url: "/sajproj/natureza/cadastrar" },
                            { text: "Visualizar", url: "/sajproj/natureza/visualizar" }              
                        ] 
                    },

                    {
                        id: "comarca", 
                        itemdata: [
                            { text: "Cadastrar", url: "/sajproj/comarca/cadastrar" },
                            { text: "Visualizar", url: "/sajproj/comarca/visualizar" }              
                        ] 
                    },

                    {
                        id: "vara", 
                        itemdata: [
                            { text: "Cadastrar", url: "/sajproj/vara/cadastrar" },
                            { text: "Visualizar", url: "/sajproj/vara/visualizar" }              
                        ] 
                    },
/*
                    {
                        id: "contato", 
                        itemdata: [
                            { text: "Cadastrar", url: "/sajproj/contato/cadastrar" },
                            { text: "Visualizar", url: "/sajproj/contato/visualizar" }              
                        ] 
                    },
                   */ 
                    {
                        id: "sair",
                        itemdata: [
							{ text: "Radio", url: "http://music.yahoo.com/launchcast" },
							{ text: "Travel", url: "http://travel.yahoo.com" },
							{ text: "TV", url: "http://tv.yahoo.com" }
                        ]
                    }                    
                ];


                /*
                     Subscribe to the "beforerender" event, adding a submenu 
                     to each of the items in the MenuBar instance.
                */

                oMenuBar.subscribe("beforeRender", function () {

                    if (this.getRoot() == this) {

                        //this.getItem(0).cfg.setProperty("submenu", aSubmenuData[0]);
                        this.getItem(1).cfg.setProperty("submenu", aSubmenuData[1]);
                        this.getItem(2).cfg.setProperty("submenu", aSubmenuData[2]);
                        this.getItem(3).cfg.setProperty("submenu", aSubmenuData[3]);
                        this.getItem(4).cfg.setProperty("submenu", aSubmenuData[4]);
                        this.getItem(5).cfg.setProperty("submenu", aSubmenuData[5]);
                        this.getItem(6).cfg.setProperty("submenu", aSubmenuData[6]);
                        //this.getItem(7).cfg.setProperty("submenu", aSubmenuData[7]);
                        this.getItem(8).cfg.setProperty("submenu", aSubmenuData[8]);

                    }

                });


                /*
                     Call the "render" method with no arguments since the 
                     markup for this MenuBar instance is already exists in 
                     the page.
                */

                oMenuBar.render();         
            
            });

        </script>

    </head>
    <body class="yui-skin-sam" id="yahoo-com">

        <div id="doc" class="yui-t1">
            

            <div id="bd">

                <!-- start: primary column from outer template -->
                <div id="yui-main">
                    <div class="yui-b">
                        <!-- start: stack grids here -->

                        <div id="productsandservices" class="yuimenubar yuimenubarnav">
                            <div class="bd">
                                <ul class="first-of-type">
                                
                                    <li class="yuimenubaritem first-of-type">
                                        <a class="yuimenubaritemlabel" href="/sajproj/busca/buscar">Buscar</a>
                                    </li>
                                    <li class="yuimenubaritem">
                                        <a class="yuimenubaritemlabel" href="javascript:void(0);">Processos</a>
                                    </li>
                                    <li class="yuimenubaritem">
                                        <a class="yuimenubaritemlabel" href="javascript:void(0);">Partes</a>
                                    </li>
                                    <!-- 
                                    <li class="yuimenubaritem">
                                        <a class="yuimenubar434itemlabel" href="javascript:void(0);">Clientes</a>
                                    </li>
                                     -->
                                    <li class="yuimenubaritem">
                                        <a class="yuimenubar434itemlabel" href="javascript:void(0);">Clientes/Contatos</a>
                                    </li>
                                    <li class="yuimenubarit434em">
                                        <a class="yuimenubar434itemlabel" href="javascript:void(0);">Natureza</a>
                                    </li>
                                    <li class="yuimenubarit434em">
                                        <a class="yuimenubar434itemlabel" href="javascript:void(0);">Comarca</a>
                                    </li>
                                    <li class="yuimenubarit434em">
                                        <a class="yuimenubar434itemlabel" href="javascript:void(0);">Vara</a>
                                    </li>
                                    <!-- 
                                    <li class="yuimenubarit434em">
                                        <a class="yuimenubar434itemlabel" href="javascript:void(0);">Contatos</a>
                                    </li>
                                     -->
                                    <li class="yuimenubarit434em">
                                        <a class="yuimenubar434itemlabel" href="/sajproj/auth/logout">Sair</a>
                                    </li>
                                </ul>
                            </div>
                        </div>


                        <!-- end: stack grids here -->
                    </div>
                </div>
                <!-- end: primary column from outer template -->

                <!-- start: secondary column from outer template -->
               
                <!-- end: secondary column from outer template -->
            </div>
            
        </div>
        
    </body>
</html>