<br />
<form id="processos" name="processos" action="/cliente/visualizar" method="post">

<link rel="stylesheet" type="text/css" href="/script/yui/fonts/fonts-min.css" />
<link rel="stylesheet" type="text/css" href="/script/yui/paginator/assets/skins/sam/paginator.css" />
<link rel="stylesheet" type="text/css" href="/script/yui/datatable/assets/skins/sam/datatable.css" />
<script type="text/javascript" src="/script/yui/yahoo-dom-event/yahoo-dom-event.js"></script>
<script type="text/javascript" src="/script/yui/connection/connection-min.js"></script>



<!--begin custom header content for this example-->
<style type="text/css">
    #paginated {
        text-align: center;
    }
    #paginated table {
        margin-left:auto; margin-right:auto;
    }
    #paginated, #paginated .yui-dt-loading {
        text-align: center; background-color: transparent;
    }
</style>

<!--end custom header content for this example-->

</head>

<!-- Caixa de busca -->
<table border="0" width="100%">
	<tr>
		<td colspan="8" nowrap="nowrap">
			<input type="text" id="parametrobusca" name="parametrobusca" value="" class="input" style="width:89%">
			<input type="submit" id="buscar" name="buscar" value="Pesquisar" class="button" width="10%">
		</td>
	</tr>
	<tr><td colspan="8">&nbsp;</td></tr>
</table>

<!-- Mostra o numero de registros encontrados -->
<table border="0" align="center">
	<tr>
		<td align="center" colspan="8" class="message"><?= $this->message; ?></td>
	</tr>
	<?php if ($this->nmclientes > 0): ?>
	<tr><td align="center" colspan="8">Foram encontrados <strong><?=$this->nmclientes ?></strong> clientes cadastrados</td></tr>
	<?php else: ?>
	<tr><td align="center" colspan="8" class="message">Nenhum cliente foi encontrado!</td></tr>
	<?php endif; ?>
</table>

<?php
	$json =
		"{'recordsReturned':" . $this->nmclientes . ",
		'totalRecords':" . $this->nmclientes . ",
		'startIndex':0,'sort':null,'dir':'asc','pageSize':504,'records':[";

	$i = 0;
	foreach($this->clientes as $key=>$cliente) {
		$json.=
			"{'id':'" . $cliente->id . "',
			'acao':
			'<a href=\"javascript:void(0);\" onclick=\"javascript:confirmExclusao(\'/cliente/excluir/id/\' + " . $cliente->id . ")\"><img src=\"/images/excluir.gif\" border=\"0\"></a>&nbsp;<a href=\"/cliente/editar/id/" . $cliente->id . "\"><img src=\"/images/editar.gif\" border=\"0\"></a>&nbsp;<a href=\"javascript:void(0);\" onclick=\"javascript:alert(\'" . $this->detalhes[$key] . "\')\"><img src=\"/images/visualizar.gif\" title=\"Detalhes\" border=\"0\"></a>',
			'nome':'" . addslashes($cliente->nome) . "',
			'inventariante':'" . $cliente->inventariante . "',
			'cpf':'" . $cliente->cpf . "',
			'celular':'" . $cliente->celular . "',
			'telefone':'" . $cliente->telefone . "',
			'telefone_comercial':'" . $cliente->telefone_comercial . "',
			'email':'" . $cliente->email . "'
			}";
		$i++;
		// Insere virgula entre os registros
		$json.= ( $i < $this->nmclientes ) ? "," : "";
	}
	$json.= "]}";

?>


<body class=" yui-skin-sam">



<!--BEGIN SOURCE CODE FOR EXAMPLE =============================== -->

	<div id="paginated"></div>

	<script type="text/javascript">
	YAHOO.util.Event.onDOMReady(function() {
	    YAHOO.example.ClientPagination = function() {
	    	var myColumnDefs = [
				{key:"acao", label:"Acao"},
				{key:"nome", label:"Nome", sortable:true},
				{key:"inventariante", label:"Inventariante", sortable:true},
				{key:"cpf", label:"CPF", sortable:true},
				{key:"celular", label:"Celular", sortable:true},
				{key:"telefone", label:"Telefone", sortable:true},
				{key:"telefone_comercial", label:"Telefone Comercial", sortable:true},
				{key:"email", label:"Email", sortable:true}
	    	];

	    	var dados = <?=$this->json2; ?>;

	        //var myDataSource = new YAHOO.util.DataSource("assets/php/json_proxy.php?");
	        var myDataSource = new YAHOO.util.DataSource(dados);
	        myDataSource.responseType = YAHOO.util.DataSource.TYPE_JSON;
	        myDataSource.responseSchema = {
	            resultsList: "records",
	            fields: ["acao","nome","inventariante","cpf","celular","telefone","telefone_comercial","email"]
	        };

	        var oConfigs = {
	                paginator: new YAHOO.widget.Paginator({
	                    rowsPerPage: 15
	                }),
	                sortedBy : {key:"nome", dir:"desc"},
	                initialRequest: "results=504"
	        };
	        var myDataTable = new YAHOO.widget.DataTable("paginated", myColumnDefs,
	                myDataSource, oConfigs);

	        return {
	            oDS: myDataSource,
	            oDT: myDataTable
	        };
	    }();
	});
	</script>

	<script type="text/javascript" src="/script/yui/json/json-min.js"></script>
	<script type="text/javascript" src="/script/yui/element/element-beta-min.js"></script>
	<script type="text/javascript" src="/script/yui/paginator/paginator-min.js"></script>
	<script type="text/javascript" src="/script/yui/datasource/datasource-min.js"></script>
	<script type="text/javascript" src="/script/yui/datatable/datatable-min.js"></script>

</form>
