<br />
<form id="processos" name="processos" action="/parte/visualizar" method="post">
<?php //echo time("22/12/2008");  
		//echo date("d/m/Y", "1239884007");
		//echo "|" . (string)$this->nmregistros; ?>
<table border="0" width="100%">
	<tr>
		<td colspan="8" nowrap="nowrap">
			<input type="text" id="parametrobusca" name="parametrobusca" value="" class="input" style="width:89%">
			<input type="submit" id="buscar" name="buscar" value="Pesquisar" class="button" width="10%">
		</td>
	</tr>
	<tr><td colspan="8">&nbsp;</td></tr>
</table>
<table border="0" class="lista_naturezas" align="center">
	<tr>
		<td align="center" colspan="8" class="message"><?= $this->message; ?></td>
	</tr>
	<?php if ($this->nmpartes > 0): ?>
	<tr><td align="center" colspan="8">Foram encontrados <strong><?=$this->nmpartes ?></strong> partes cadastradas</td></tr>
	<tr>
		<td nowrap="nowrap" class="brancob_11"  bgcolor="gray">Processo</td>
		<td nowrap="nowrap" class="brancob_11"  bgcolor="gray">Cliente</td>
		<td nowrap="nowrap" class="brancob_11"  bgcolor="gray">Parte</td>
		<td nowrap="nowrap" class="brancob_11"  bgcolor="gray">Matr&iacute;cula</td>
		<td nowrap="nowrap" class="brancob_11"  bgcolor="gray">CPF</td>
		<td nowrap="nowrap" class="brancob_11"  bgcolor="gray">RG</td>
		<td nowrap="nowrap" class="brancob_11"  bgcolor="gray">&nbsp;</td>
	</tr>
	<?php else: ?>
	<tr><td align="center" colspan="8" class="message">Nenhuma parte foi encontrada!</td></tr>
	<?php endif; ?>
	<?php $i = 0?>
	<?php foreach($this->partes as $parte) : ?>
	<?php $bgcolor = ($i % 2 == 0) ? "#eeeeee" : "" ?>
	<tr background="#ded">
		<td nowrap="nowrap" class="cinza_11" bgcolor=<?=$bgcolor?>>
			<?php echo formataNumeroProcesso($parte->findParentProcesso()->numero_processo); ?>			
		</td>
		<td nowrap="nowrap" class="cinza_11" bgcolor=<?=$bgcolor?>>
			<?php echo $parte->findParentCliente()->nome; ?>			
		</td>
		<td nowrap="nowrap" class="cinza_11" bgcolor=<?=$bgcolor?>>
			<?php echo $parte->nome_parte; ?>			
		</td>
		<td nowrap="nowrap" class="cinza_11" bgcolor=<?=$bgcolor?>>
			<?php echo $parte->numero_matricula; ?>			
		</td>
		<td nowrap="nowrap" class="cinza_11" bgcolor=<?=$bgcolor?>>
			<?php echo $parte->cpf; ?>			
		</td>
		<td nowrap="nowrap" class="cinza_11" bgcolor=<?=$bgcolor?>>
			<?php echo $parte->rg; ?>			
		</td>
		
		<td  width="50px" nowrap="nowrap" bgcolor=<?=$bgcolor?>>		
			<a href="<?= "/parte/editar/id/" . $parte->id?>">
				<img src="/images/editar.gif" border="0"></a>
			<a href="#" onclick="javascript:confirmExclusao('/parte/excluir/id/' + <?=$parte->id?>)">
				<img src="/images/excluir.gif" border="0"></a>
				
		</td>
	</tr>
	<?php $i++; ?>
	<?php endforeach; ?>

</table>
</form>

<?php 

function formataNumeroProcesso($nmProcesso) {
	// 023.95.052005-1
	// 239.50.520051-1
	// 023..9.5.0520-0 
	//substr('abcdef', 0, 4);  // abcd
	//echo $nmProcesso . "=";
	$nmProcesso = str_pad($nmProcesso, 12, "0", STR_PAD_LEFT);
	
	// 023.95.052005-1
	$parte1 = substr($nmProcesso, 0, 3);
	$parte2 = substr($nmProcesso, 3, 2);
	$parte3 = substr($nmProcesso, 5, 6);
	$parte4 = substr($nmProcesso, 11, 1);
	return $parte1 . "." . $parte2 . "." . $parte3 . "-" . $parte4;
}
?>